### ISSUE TITLE
Path substitution does not work with YAML.subMaps

### ISSUE THREAD

**Issue by tokee** [kb-dk/kb-util#45]
The recent addition of #43 has a bug where `YAML.getSubMap("somepath").get("foo")` does not work when substitution is used in the nested value:
```
somepath:
  foo: ${path:elsewhere:inner}

elsewhere:
  inner: myvalue
```

This is because `YAML.getSubMap(...)` creates a new independent `YAML` where all resolving is contained to the new sub-YAML structure. The fix is to use the same substitutions for the new `YAML` as for the old.
