### ISSUE TITLE
Problem with conditionals

### ISSUE THREAD

**Issue by tokee** [kb-dk/kb-util#67]
`OaiHarvestClientIntegrationTest` in [ds-datahandler](https://github.com/kb-dk/ds-datahandler/) uses the code
```Java
    oaiTarget.setUsername(conf.getString("integration.oaiTargets[1].user"));
```
against a config like
```
integration:
  oaiTargets:
    - name: pvica5.devel
      datasource: ds.radiotv
      url: <serverurl>
      user: <user>
      password: <password>
      metadataPrefix: XIP_full_schema
      description: Radio- of TV-udsendelser

    - name: pvica7.devel
      datasource: ds.radiotv
      url: <serverurl>
      user: <user>
      password: <password>
      metadataPrefix: xip
      description: Radio- of TV-udsendelser
      filter: preservica
      dateStampFormat: datetime
      dayOnly: true
      startDay: '2024-03-01'
```
It would be a lot cleaner to write
```Java
    oaiTarget.setUsername(conf.getString("integration.oaiTargets[name=pvica7.devel].user"));
```
but this does not work!?
